### ISSUE TITLE
ValueError on unexpected hyprctl version

### ISSUE THREAD

**Issue by TheEaterr** [fdev31/wlr-layout-ui#10]
I run nixos and the output of my `hyprctl -j version` is, for some reason:

```
{
    "branch": "",
    "commit": "",
    "dirty": true,
    "commit_message": "",
    "commit_date": "",
    "tag": "",
    "commits": "",
    "flags": []
}
```

Which causes the following error when launching wlrui:

```
Traceback (most recent call last):
  File "/nix/store/azi273kz8q49caqj8nwjpjbnnfrwd1sa-wlr-layout-ui-1.6.11/bin/.wlrlui-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/azi273kz8q49caqj8nwjpjbnnfrwd1sa-wlr-layout-ui-1.6.11/lib/python3.11/site-packages/wlr_layout_ui/__init__.py", line 86, in main
    load()
  File "/nix/store/azi273kz8q49caqj8nwjpjbnnfrwd1sa-wlr-layout-ui-1.6.11/lib/python3.11/site-packages/wlr_layout_ui/screens.py", line 85, in load
    major = int(version[0])
            ^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
```

Would it be possible to also assume a `new_hyprland` when running into `ValueError` while parsing (i.e. by adding in the except below) ?

https://github.com/fdev31/wlr-layout-ui/blob/1a43a87fec97d3ae21628973a292f5ac82e27817/src/wlr_layout_ui/screens.py#L56-L63

**Comment by bnlrnz** [comment]
Hi, I'm maintaining the nix package of wlr-layout-ui.
There was a bug in the older hyprland nix package that lead to hyprctl not providing the version information. ([see this issue](https://github.com/NixOS/nixpkgs/issues/317234#event-13176664418))

This is fixed as of hyprland version 0.41.1 (in nix channel 24.11 and unstable, also backported to 24.05) and I am currently [doing an upgrade](https://github.com/NixOS/nixpkgs/pull/322261) of the wlr-layout-ui package to support this fixes.

It should only take a few days, I guess.

**Comment by TheEaterr** [comment]
Thank you very much ! I'll close the issue when the upgrade goes through.

**Comment by TheEaterr** [comment]
It's solved now, thank you!
