### ISSUE TITLE
AUR package problem

### ISSUE THREAD

**Issue by mhkarimi1383** [fdev31/wlr-layout-ui#11]
/home/karimi/.cache/yay/wlr-layout-ui/PKGBUILD: line 27: cd: /home/karimi/.cache/yay/wlr-layout-ui/src/wlr-layout-ui: No such file or directory

but sources are available as

~/.cache/yay/wlr-layout-ui/src/wlr-layout-ui-1.6.14

**Comment by fdev31** [comment]
Should be fixed now.
