### ISSUE TITLE
countdown option

### ISSUE THREAD

**Issue by Spike1377** [fdev31/wlr-layout-ui#4]
sometimes you change your screen resolution and you cant see anything and you gotta wait for it to go back to normal, you should add this to wlr gui, or if you do have it make it enabled by default. bcus right now it just sets the reslulton and dosn't ask if you want to keep changes with a countdown saying no.

you have seen it before

maybe wayland it too good and dosnt need it or something
![](https://techcult.com/wp-content/uploads/2019/03/How-to-Change-Screen-Resolution-in-Windows-10.png)

**Comment by fdev31** [comment]
You are right, it would be a nice feature to implement, I'll think about it.
