### ISSUE TITLE
Provide License

### ISSUE THREAD

**Issue by bnlrnz** [fdev31/wlr-layout-ui#7]
Hi Fabien,

Could you provide a license for wlr-layout-ui?

I like your project and would like to add it as a package to the Nix package manager/NixOS. Packages without a license will be marked as "unfree" software in Nix, which has some drawbacks for the package.
Since you already provide the project as open source on github, a typical license would not hurt. A suggestion could be the MIT license, which is also used by wlr-randr and tomli.

**Comment by fdev31** [comment]
I updated the sources, must it be re-released or fine as is?

**Comment by bnlrnz** [comment]
Thank you. I was able to apply the license for the "older" release. It does not have to be in the sources of the release I am packaging right now (1.4.3). This is my first time contributing a package to the Nix environment. I will try to update the package with new releases from time to time.

**Comment by bnlrnz** [comment]
The Nix member reviewing my attempt to package wlr-layout-ui did run into the hyprland version check bug. (fixed in PR #5)

Would you be so kind to provide a new release including the patch (and the new license).

Sorry for the back and forth 🙏

**Comment by fdev31** [comment]
1.4.7 should be suitable... tell me if not.
