### ISSUE TITLE
Use hyprland commit date instead of tagged release

### ISSUE THREAD

**Issue by Evangelospro** [fdev31/wlr-layout-ui#8]
There is an issue in https://github.com/fdev31/wlr-layout-ui/blob/05b662624c614a4642c358bec25cd49bce8e800d/src/wlr_layout_ui/screens.py#L84-L91
Because someone may not be using a tagged release, thus his output of `hyprctl -j version`, will look something like this 
```bash
hyprctl -j version
{
    "branch": "main",
    "commit": "33e0bb14786dc22a0c82eaaf097b469d3fdeceea",
    "dirty": false,
    "commit_message": "wlr-output-power: move to new impl",
    "commit_date": "Mon Apr 29 03:38:24 2024",
    "tag": "",
    "commits": 58,
    "flags": []
}
```
So I would maybe suggest fetching the git commit date maybe and comparing since whenever "new_hyprland" was released? Doesn't sound like the most robust solution but I think it should work

**Comment by fdev31** [comment]
I'll just change the default to assume it's a recent hyprland, untagged builds are generally people running recent versions IMO... and 0.37 isn't very bleeding edge anymore!
Thank you for the problem report :)
